### ISSUE TITLE
商品封面图无法上传

### ISSUE THREAD

**Issue by HLPBason** [iamdarcy/hioshop-admin#50]
@iamdarcy 作者大大你好，我这边部署后端操作商品列表，发现图片无法上传，商品图片选好后点击确定保存下方总是提示请选择商品图片，您知道是什么原因吗
<el-form-item label="商品图片" prop="list_pic_url" v-if="infoForm.list_pic_url" class="image-uploader-diy new-height">
						<div class="index-image">
							<el-image :preview-src-list="previewList" v-if="infoForm.list_pic_url" :src="infoForm.list_pic_url" @click="previewIndexImg"
							 class="image-show" fit="cover"></el-image>
							<div class="o-shadow" @click="delePicList">
								<i class="el-icon-delete"></i>
							</div>
						</div>
					</el-form-item>
					<el-form-item label="商品图片" prop="list_pic_url" v-if="!infoForm.list_pic_url">
						<el-upload name="file" ref="upload" class="upload-demo" :action="qiniuZone" :on-success="handleSuccess"
						 :before-upload="indexImgBefore" :auto-upload="true" list-type="picture-card" :data="picData" :http-request="uploadIndexImg">
							<el-button size="small" type="primary">点击上传</el-button>
							<div slot="tip" **class="el-upload__tip">**只能上传jpg/png文件**</div>**
						</el-upload>
					**</el-form-item>**

**Comment by HLPBason** [comment]
已解决

**Comment by fh1999** [comment]
你好 能请问下七牛图片上传怎么解决的吗？我也遇到了同样的问题
